name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          9.0

    - uses: actions/checkout@v4

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore /property:ContinuousIntegrationBuild=True

#    - name: Test
#      run: dotnet test --configuration Release --no-restore --no-build

    - name: Pack
      run: dotnet pack --configuration Release --no-restore --no-build -o artifacts

    - name: Publish
      uses: actions/upload-artifact@v4
      with:
        name: packages
        path: 'artifacts/*.*nupkg'
